[1]
label = duie_train
model_type = spert
# model_path = bert-base-cased
model_path = D:\cache\huggingface\hub\models--bert-base-chinese\snapshots\8f23c25b06e129b6c986331a13d8d025a92cf0ea
# tokenizer_path = bert-base-cased
tokenizer_path = D:\cache\huggingface\hub\models--bert-base-chinese\snapshots\8f23c25b06e129b6c986331a13d8d025a92cf0ea
train_path = data/datasets/DuIE2.0/duie2.0_small/train.json
valid_path = data/datasets/DuIE2.0/duie2.0_small/dev.json
types_path = data/datasets/DuIE2.0/duie2.0_small/duie_types.json
train_batch_size = 2 # 训练批次大小
eval_batch_size = 1 # 评估批次大小
neg_entity_count = 100 # 负样本(实体)数量  其实就是某个片段(span)不属于实体，那此时这个片段就是负样本
neg_relation_count = 100 # 负样本(关系)数量  其实就是某两个entity之间没有关系，那么这两个entity就属于负样本
epochs = 10 # 总的训练epoch
lr = 5e-5 # 基础学习率
lr_warmup = 0.1 # warmup的学习率
weight_decay = 0.01 # l2惩罚性系数
max_grad_norm = 1.0 # 梯度的截断值
rel_filter_threshold = 0.4 # 关系过滤系数
size_embedding = 25 # 长度embedding的维度大小
prop_drop = 0.1
max_span_size = 10 # 在当前业务中最长实体为10个token
store_predictions = true
store_examples = true
sampling_processes = 0 # 数据加载的进程数目
max_pairs = 1000
final_eval = false  # 是不是只在最后训练完成后进行评估
log_path = data/DuIE2.0/log/
save_path = data/DuIE2.0/save/